class players(db.Model):
    playerID = db.Column(db.Integer, primary_key=True)
    playerFirstName = db.Column(db.String, nullable=False)
    playerLastName = db.Column(db.String, nullable=False)

class war(db.Model):
    charID = db.Column(db.Integer, primary_key=True)
    playerID = db.Column(db.Integer)
    charName = db.Column(db.String)
    charBio = db.Column(db.String)
    charBlurb = db.Column(db.String)
    charEpitaph = db.Column(db.String)
    charImg = db.Column(db.String)
    charDead = db.Column(db.Integer)
    charClass = db.Column(db.String)
    charCareer = db.Column(db.String)
    charDistMark = db.Column(db.String)
    charStar = db.Column(db.String)
    charStatus = db.Column(db.String)
    charCareerGroup = db.Column(db.String)